import { whiteLogo,workoutCartBg,Biceps, } from "@/assets"
export const CourseListData=[
        {   _id:1,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:2,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:3,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:4,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:5,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:6,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:7,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:8,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:9,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
        {   _id:10,
            title:'סקווט קלאסי',
            subTitle:'ירך קדמית',
            cartBg:workoutCartBg,
            whiteLogo:whiteLogo,
            icon:Biceps,
        },
       
        

]