import {workoutCartBg,whiteLogo,TimeCircle,Calories} from'../assets/index'
export const workOutData=[
    {  _id:1,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
    {
        _id:2,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
    {
        _id:3,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
    {
        _id:4,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
    {
        _id:5,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
    {
        _id:6,
        title:'אימון חיטוב רגליים ויד קדמית',
        caloriesTitle:'180 קל׳',
        timeTilte:'20 דקות',
        cartBg:workoutCartBg,
        whiteLogo:whiteLogo,
        timeIcon:TimeCircle,
        calories:Calories,
    },
]